global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "board-game-tournaments-app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          [
            "board-game-tournaments-gateway:8080",
            "notification-service:8083",
            "analytics-service:8081",
            "board-game-tournaments-schedule-service:8082",
          ]